### PR TITLE
Add MAX! adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**
Can you please add this to https://github.com/mozilla-iot/addon-builder

### CODE REVIEW

**Comment by mrstegeman** [comment]
This package has a binary module in it. Do you need to make any changes to get it to build, or is this safe to add to our add-on builder?

**Comment by tim-hellhake** [comment]
I added the `package.sh` from a project which is already in the `addon-builder`.
https://github.com/tim-hellhake/max-adapter/commit/27d5188e9814f752a3d01b886bc1f3a591dc6b17 should be safe.

**Comment by mrstegeman** [comment]
```
File missing for package "max-adapter": lib/index.js
The command "./check-list.py" exited with 1.
```

**Comment by tim-hellhake** [comment]
The `npm run build` step before `pack` was missing.
I also updated the checksum generation.
Tag `0.1.2` should work.

**Comment by mrstegeman** [comment]
Build is still failing with the same error. Other than the node modules, the only contents of the package are:

```
package/README.md
package/LICENSE
package/package.json
package/SHA256SUMS
```

**Comment by tim-hellhake** [comment]
If I run it locally everything is there o.O

**Comment by tim-hellhake** [comment]
The `max-adapter` module in https://github.com/mozilla-iot/addon-builder is at `27d5188/0.1.1`.

**Comment by mrstegeman** [comment]
The submodules get auto-updated by the builder script.

**Comment by mrstegeman** [comment]
Ah. From the builder log:

```
> tsc -p .
sh: tsc: command not found
```

**Comment by tim-hellhake** [comment]
The dev dependencies are missing.

**Comment by mrstegeman** [comment]
Good now?

**Comment by tim-hellhake** [comment]
Ok try again

**Pull request merged**
