### PR TITLE
Square theme - version 0.0.1

### PR DESCRIPTION
**Pull request by flatsiedatsie**
An experimental theme.
- Removes the octopus view
- Adds setpoint buttons

### CODE REVIEW

**Comment by flatsiedatsie** [comment]
square-theme

**Comment by flatsiedatsie** [comment]
By the way, it only works in Chromium.

**Comment by mrstegeman** [comment]
Ok, a couple things I see here:
1. In your list entry (this PR), you should set the language to `none` and remove the `versions` array. See #565 
2. Since there is only a UI piece, the Python bits should be removed from the package.
3. Remove the `exec` line from your manifest, since there's no back end.

**Comment by mrstegeman** [comment]
This is pretty neat. I've started playing with it now.
1. Please rebase this PR on master so that the tests pass.
2. The `architecture` should be `any`.
3. I added all of the virtual things from the Virtual Things add-on. Several things don't show icons at all, and some show blue text which is really hard to read.

Screenshot_2019-11-19 WebThings Gateway

Other notes:
1. If you install the virtual things add-on and set the `randomizePropertyValues` flag, it's really nice for testing.
2. This works the same for me in both Chrome and Firefox Nightly, so I guess the new features will be coming soon to Firefox (stable).

**Comment by flatsiedatsie** [comment]
I can't fix those icon issues, because the Gateway hardwires some state displays as images (which is an issue I'd say).

I don't know how to "rebase this PR on master", but I will create a new request.

**Comment by benfrancis** [comment]
This is a cool idea, but I suspect this is going to be quite brittle (break very easily).

Rather than try to hack the CSS of the existing web components, I wonder whether a better long term direction to allow this kind of thing would be to find a way to package up custom web components to represent particular web thing [capabilities](https://iot.mozilla.org/schemas/#capabilities). As well as being able to replace the default representation of already supported capabilities, this could be a way to add support for new capabilities or different schema repositories like iotschema.org.

I've filed https://github.com/mozilla-iot/gateway/issues/2302

**Comment by mrstegeman** [comment]
> I can't fix those icon issues, because the Gateway hardwires some state displays as images (which is an issue I'd say).

Fixed that here: https://github.com/mozilla-iot/gateway/pull/2304

**Pull request closed without merging**
