### PR TITLE
Add Matrix Adapter

### PR DESCRIPTION
**Pull request by jaller94**
Allows to post custom or predefined unencrypted messages to one Matrix room.

Screenshot_2020-06-19_13-49-41

---

Screenshot_2020-06-19 Riot IoT room

---

Screenshot_2020-06-19_13-52-55

---

Screenshot_2020-06-19_13-51-28

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Nice!

> Name mismatch for package "matrix-adapter": display_name from package.json "Matrix chat" doesn't match name from list.json "Matrix"

😬

**Comment by tim-hellhake** [comment]
> Name mismatch for package "matrix-adapter": display_name from package.json "Matrix chat" doesn't match name from list.json "Matrix"

😬

**Comment by tim-hellhake** [comment]
> Homepage mismatch for package "matrix-adapter": homepage from package.json "https://gitlab.com/webthings/matrix-adapter#readme" doesn't match homepage_url from list.json "https://gitlab.com/webthings/matrix-adapter"

Next one 😬

**Comment by tim-hellhake** [comment]
🙌

**Comment by jaller94** [comment]
@mrstegeman Do you host them in a central S3 bucket to ensure their availability?
How do you commonly receive updates? Should I change the URL, make the CI tests pass, and then you download it, upload it to S3 and add a commit every time?

**Comment by mrstegeman** [comment]
They go into S3 to ensure availability and to make sure the package is unchanged from when I last reviewed it.

When you want to update, build a new release and open a PR here with a link to the package and the updated checksum. I’ll review it and move the package to S3 and update your PR with the S3 URL.

**Pull request merged**
