### PR TITLE
Internet radio 1.0.1

### PR DESCRIPTION
**Pull request by flatsiedatsie**

### CODE REVIEW

**Comment by mrstegeman** [comment]
The package includes a pyalsaaudio binary, but it's not used by the code.

**Comment by flatsiedatsie** [comment]
It should be, in the clock function. It's used to find out the system volume, and make the volume property reflect the actual volume.

**Comment by mrstegeman** [comment]
Ah, I see it now. Unfortunately, that is only going to work on Linux, negating the cross-platform support I added. This should make things easier: https://github.com/flatsiedatsie/internet-radio/pull/6

**Comment by flatsiedatsie** [comment]
Thanks for the fix. I wanted to suggest making this a Raspberry Pi only feature, but you beat me to it.

**Comment by mrstegeman** [comment]
Oops! Apologies.

**Pull request merged**
