### PR TITLE
Update Max! adapter to 0.1.7

### PR DESCRIPTION
**Pull request by tim-hellhake**
Please run the addon builder and add checksums.

tim-hellhake/max-adapter#1

### CODE REVIEW

**Comment by mrstegeman** [comment]
You'll need to add `rm -rf node_modules/.bin` to your `package.sh`.

```
Checksum missing for file "/home/runner/work/addon-list/addon-list/package/node_modules/.bin/tsserver" in package "max-adapter"
```

**Comment by tim-hellhake** [comment]
done

**Comment by mrstegeman** [comment]
```
File missing for package "max-adapter": lib/index.js
```

**Comment by tim-hellhake** [comment]
> File missing for package "max-adapter": lib/index.js

I can't image why.
I'm also building the package and it seems to be ok.

**Comment by mrstegeman** [comment]
Ah, this probably has something to do with it:
```
sh: 1: tsc: not found
```

**Comment by tim-hellhake** [comment]
Yeah that makes sense.

**Comment by tim-hellhake** [comment]
It should work now.
The `rm -rf node_modules/.bin` killed the TypeScript compiler.

**Pull request merged**
