### PR TITLE
Add Alexa adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**
Alexa, please merge my PR

### CODE REVIEW

**Comment by mrstegeman** [comment]
This is an interesting workaround. I have a couple suggestions:

1. Instead of handling the first boolean property you find ([here](https://github.com/tim-hellhake/alexa-adapter/blob/master/alexa-adapter.js#L41)), you should probably look for properties with `@type` of `OnOffProperty`.
2. The README seems to cut off when describing which Alexa skill to add. It wasn't until I read the code that I figured out you were simulating a Hue bridge.

**Comment by hobinjk** [comment]
The description should state that it only has support for boolean devices through the hue bridge API since otherwise people will expect to be able to control all of their devices

**Comment by tim-hellhake** [comment]
@mrstegeman done

**Comment by tim-hellhake** [comment]
@hobinjk done

**Comment by mrstegeman** [comment]
@hobinjk Do you have an Echo that you can test this with?

**Comment by benfrancis** [comment]
I suggest renaming this add-on to more accurately reflect what it does, as simply calling it "Alexa" will probably make people think it allows you to control all the devices attached to the gateway using Alexa.

Perhaps something like "Alexa Philips Hue Controller".

**Comment by tim-hellhake** [comment]
Well that's what it does 😄
Except for the fact that currently only the boolean properties are supported.

**Comment by hobinjk** [comment]
I'll be able to test this out later today.

The terminology of "Emulated Hue Bridge"/"Hue Emulation" is pretty standard, see https://www.home-assistant.io/components/emulated_hue/ and https://www.openhab.org/addons/integrations/hueemulation/.

**Comment by tim-hellhake** [comment]
@hobinjk
Which doesn't mean it's a good title.
The main purpose of the addon is making devices controllable by Alexa.
Hue emulation is a technical detail which makes it possible.
I guess most users will simply search for 'Alexa'.

**Comment by tim-hellhake** [comment]
@benfrancis renamed

**Comment by hobinjk** [comment]
This looks reasonable! I'm going to stop adding more fuel to the name bikeshed fire :)

When trying to test this it keeps crashing because the server in hue-hub-emulator wants to listen on port 80 which the gateway is already using.

If I change the port there I instead get a `FetchError: invalid json response body at http://localhost:8080/things reason: Unexpected token F in JSON at position 0` which appears to be caused by the fact that I have SSL set up on my gateway. Poking around with curl, the only fetch attempt that worked was https://localhost:4443/things with certificate validation skipped.

**Comment by tim-hellhake** [comment]
> When trying to test this it keeps crashing because the server in hue-hub-emulator wants to listen on port 80 which the gateway is already using.

I took the port number from the `default.js`.
If I try to advertise another port to the echo it still tries to contact port 80.
Without adding another route to the gateway there is nothing a can do.
Maybe this is a case for an extension addon?

**Comment by mrstegeman** [comment]
@tim-hellhake Should we just close this for now, since there's presently no way to make it work? We've been discussing the possibility of allowing service add-ons to add API routes to the gateway's server, which I think would handle this use case. Until then, though, it doesn't seem like this is going to move forward at all.

**Pull request closed without merging**
