### PR TITLE
Add yamaha adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**

### CODE REVIEW

**Comment by tim-hellhake** [comment]
@rhladky as soon this is merged you can test the adapter

**Comment by mrstegeman** [comment]
Small nitpicks:
* Typo ("number of seconds"):
  * https://github.com/tim-hellhake/yamaha-adapter/blob/master/manifest.json#L31
  * https://github.com/tim-hellhake/yamaha-adapter/blob/master/package.json#L48
* `MultiLevelSensor` doesn't really apply, since the volume (`LevelProperty`) is not read-only. `MultiLevelSwitch` would be better.
  * https://github.com/tim-hellhake/yamaha-adapter/blob/master/src/yamaha-adapter.ts#L139
* All of your actions have the same description:
  * https://github.com/tim-hellhake/yamaha-adapter/blob/master/src/yamaha-adapter.ts#L160-L174
* Please `rm -rf node_modules/.bin` in your `package.sh` to avoid future issues.

**Comment by tim-hellhake** [comment]
> MultiLevelSwitch would be better

That makes sense.

> All of your actions have the same description

Damn, I checked every property description because they looked so similar but forgot to look after the actions.

**Comment by rhladky** [comment]
Hi @tim-hellhake . I did install and tried some basic tests.

Good news:
- The Yamaha device on my network was automatically recognized
- The Yamaha thing appeared on my Mozilla dashboard (looking like thermometer)
- When I open it, it shows "star" with various attributes and buttons (PLAY, PAUSE...)

Bad news:
- I did not find a way how to turn on Yamaha and start playing music
- Whatever button I click, nothing happens ...

**Comment by tim-hellhake** [comment]
Hi @rhladky,

>I did not find a way how to turn on Yamaha

I don't know why but I didn't add a power property 😬.
I'll add that.

>start playing music

Which source did you want to play?
I'm usually using spotify.

>Whatever button I click, nothing happens

Can you please try the following for me:
- Power on the Yamaha manually
- Play something
- Check if the volume controls works via the addon

**Pull request merged**
