### PR TITLE
Candle manager 1.1.0

### PR DESCRIPTION
**Pull request by createcandle**
fixes small issue where update process could run twice at the same time.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Hmmm... It looks like you're packaging all of the dependencies (including compiled ones), but still running the `bootstrap.py` script. You should be doing one or the other. The best solution (which takes advantage of the cross-platform arduino-cli support I added to this add-on) is this: https://github.com/createcandle/Candle-manager-addon/issues/12

**Comment by mrstegeman** [comment]
https://github.com/createcandle/Candle-manager-addon/pull/15

**Comment by createcandle** [comment]
Thank you.

Quick question: is there a way for gui extension addons to 'claim' a URL in the system? So that something like `gateway.local/candle_manager` will open the candle manger?

**Comment by mrstegeman** [comment]
Please merge the PR I just opened and I'll add your add-on to the [addon-builder](https://github.com/mozilla-iot/addon-builder).

**Comment by mrstegeman** [comment]
Still waiting on this: https://github.com/createcandle/Candle-manager-addon/pull/16

**Comment by flatsiedatsie** [comment]
It has been merged. Is there anything that still needs doing?

**Comment by mrstegeman** [comment]
Yes, I opened another PR last week: https://github.com/createcandle/Candle-manager-addon/pull/17

**Comment by mrstegeman** [comment]
As it turns out, the last PR only fixed one of the problems. This should fix the other: https://github.com/createcandle/Candle-manager-addon/pull/18

**Pull request merged**
