### PR TITLE
sensehat: Update to 0.0.4 from 0.0.3

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I7bca3477e10b4808c0c13358e553d734ab318301
Relate-to: https://github.com/rzr/sense-hat-webthing/issues/3
Signed-off-by: Philippe Coval <rzr@users.sf.net>

### CODE REVIEW

**Comment by mrstegeman** [comment]
The addon-builder is failing to build numpy (Cython, actually), at least with Python 3.5. As far as I can tell, 3.5 should be supported, so I'm not sure what's going on. Any idea?

https://github.com/mozilla-iot/addon-builder/runs/657262548?check_suite_focus=true

**Comment by rzr** [comment]
IIRC I tested on 3.7 let me try to rebuild locally.

**Comment by mrstegeman** [comment]
Fix is here: https://github.com/rzr/sense-hat-webthing/pull/6

**Comment by mrstegeman** [comment]
If you want to use your package, the URL and checksum are wrong and need to be updated. Otherwise, you'll need to merge that PR so that I can build.

**Pull request merged**
