### PR TITLE
generic-sensors-adapter: Update to v0.0.10

### PR DESCRIPTION
**Pull request by rzr**
Bug: https://github.com/rzr/mozilla-iot-generic-sensors-adapter/issues/11
Relate-to: https://github.com/mozilla-iot/addon-list/pull/54
Change-Id: I576648a50ba66abe91688359abdfa281a0ae63fa
Signed-off-by: Philippe Coval <rzr@users.sf.net>

### CODE REVIEW

**Comment by mrstegeman** [comment]
Thanks for taking care of this!

Would you have a problem with me pulling this into the [addon-builder](https://github.com/mozilla-iot/addon-builder), so that we can get builds for Node 10 and 12 as well? This is one of 4 remaining add-ons that will only work with Node 8.

**Comment by rzr** [comment]
I can do that of if you want go ahead, 
as you know I used my own builder script (and it's really slow)

node 10 should work using the @abandonware i2c module... 

Anyway I will probably a new version before next release

**Comment by mrstegeman** [comment]
Ok, I'll go ahead and merge this PR and then will try to add it to the addon-builder.

**Comment by rzr** [comment]
I just opened a PR, to use builder, but I might have missed other steps, any documentation I should look at: 

https://github.com/mozilla-iot/addon-list/pull/823

**Comment by mrstegeman** [comment]
You can not trigger an actual release build, only I can. So you’ll just have to let me know when you’re ready.

**Pull request merged**
