### PR TITLE
Add SensorTag adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**
Resolves https://github.com/mozilla-iot/gateway/issues/678
We need another cross-compile build here because of noble.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Please merge https://github.com/tim-hellhake/sensor-tag-adapter/pull/1

After that, I will attempt to rebuild and update this PR again.

**Comment by tim-hellhake** [comment]
Merged :)
Sorry, I usually create a checksum file for my github releases.
What was the problem? Is the `shasum` command missing or did the additional sha256sum file break the build?

**Comment by mrstegeman** [comment]
It was trying to run `shasum` on a non-existent file.

**Comment by mrstegeman** [comment]
Great addition, thanks!

**Pull request merged**
