### PR TITLE
Add Wemo adapter.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes mozilla-iot/gateway#621

### CODE REVIEW

**Comment by mrstegeman** [comment]
@che-wf You can add them through the UI:
1. Click _Settings_ in the main menu.
2. Click _Add-ons_.
3. Click the + at the bottom right.

If you're still having issues:
* Are you running our Raspberry Pi image, or are you running on something else?
* Are you seeing errors?

**Comment by che-wf** [comment]
I have Gateway running on my Raspberry Pi--not installed via the Gateway Image. 

I have the Add-on installed. No problems there. 

It's just not finding my switches when I scan. I'm not seeing any errors either.

**Comment by mrstegeman** [comment]
@che-wf Can you file individual issues [here](https://github.com/mozilla-iot/wemo-adapter) and [here](https://github.com/mozilla-iot/tplink-adapter) so we can discuss further?

If you could attach your `~/.mozilla-iot/log/run-app.log` file to those issues somehow, that would also be helpful.

**Comment by mrstegeman** [comment]
@che-wf Before attaching the logs, can you uninstall and reinstall those add-ons? I'd like to make sure the installation works properly.

**Comment by che-wf** [comment]
Ok. I'll take this over to the Issues page. But I uninstalled and installed again. I'm watching the console and seeing that neither can find the `gateway_addon` module.

**Comment by che-wf** [comment]
Ah! That was it.

**Pull request merged**
