### PR TITLE
Add W3C Web of Things adapter

### PR DESCRIPTION
**Pull request by jakubdybczak**
Information about this adapter can be found here:
https://github.com/jakubdybczak/w3c-web-of-things-adapter/blob/master/README.md

### CODE REVIEW

**Comment by mrstegeman** [comment]
My biggest question here is why did you decide to fork the Web Thing adapter, rather than adding the new functionality there? The W3C spec is not _super_ different from ours, so the HTTP support should be fairly easy to merge into the existing adapter.

As for MQTT, I'm curious what actual protocol spec you're basing this off of? I haven't seen any MQTT protocol bindings for the WoT spec. Any pointers?

**Comment by jakubdybczak** [comment]
We decided to fork Web Thing adapter to not combine different implementations. Yes, W3C spec is not super different, but we think that it's different enough to not combine these adapters. For example W3C HTTP binding uses long pooling for observing properties, W3C HTTP also support uri variables.

As for MQTT, yes, there is not actual protocol spec, but we wanted to support more protocols (many IoT devices can easily expose data with this protocol). Eclipse Thingweb (which is implementation of W3C WoT) also can expose data with MQTT - it's basically the same data as from HTTP binding, but with MQTT. So yes, it's not really formal, but this is another _option_ - and we stated this in README.MD

**Comment by benfrancis** [comment]
I agree with @mrstegeman that ideally this would be combined with the existing web thing adapter (and that MQTT should be kept separate).

The main difference of looking for `links` vs. `forms` should be fine, just look for both and use whichever one is there.

However, it would also would require the default web thing adapter implementing things which are not currently in the [Web Thing REST API](https://iot.mozilla.org/wot/#web-thing-rest-api) specification, like long polling for example.

@mrstegeman Can you envisage this causing any conflicts?

I'm also curious how far you are planning on taking this, @jakubdybczak? Currently it seems to just cover the very basic features provided by the [W3C's HTTP protocol binding](https://w3c.github.io/wot-thing-description/#http-binding-assertions) of `GET` and `PUT` to read and write properties and `POST` to invoke an action. Do you plan to stick to that, or to expand this to implement all the possible variations provided through declarative protocol bindings in `forms` with `op`s? E.g. it is technically possible for a W3C Thing Description to tell a client to get the value of a property with an HTTP `DELETE` request, with its result encoded as a bitmap with a MIME type of `image/bmp`...

**Comment by mrstegeman** [comment]
> @mrstegeman Can you envisage this causing any conflicts?

No, that should be easy enough to support.

**Comment by jakubdybczak** [comment]
According to your suggestion, should I get rid off MQTT bindings from my plugin - possibly release MQTT handling as seperated adapter?

Also, as you said one of way of checking API is checking if there are`links` or `forms`. 
I think that there are two ways for implementation:

1. After detecting Mozilla WebThing / W3C WoT point to one of distinct implementations
2. After detecting Mozilla WebThing / W3C WoT save this information as some kind of flag and merge two implementations by using checks (`if`'s) inside every function.

Method 2 should be fairly easy to implement, it will take less space than method 1 but code may feel less readable as there will be many flag checks. Method 1 is also more future-proof if W3C standarized WebSocket protocol in future.

What approach do you think is better?

**Comment by mrstegeman** [comment]
Personally, I don't have an issue with the MQTT support. My primary issue is with having 2 separate WoT adapters. Instead of going that route, I'd recommend opening a series of PRs for thing-url-adapter to split out the implementations as you have done in this adapter and to add support for the Eclipse implementations alongside ours. Would that be ok?

**Comment by jakubdybczak** [comment]
Yeah, it's ok. At this point I'm closing this PR.

**Pull request closed without merging**
