### PR TITLE
Update luftdaten adapter to 1.0.0

### PR DESCRIPTION
**Pull request by tim-hellhake**
tim-hellhake/luftdaten-adapter#2

### CODE REVIEW

**Comment by mrstegeman** [comment]
What do these IDs end up looking like? Would it be better to keep the `luftdaten-` prefix to avoid possible conflicts with other adapters?

https://github.com/tim-hellhake/luftdaten-adapter/commit/50fe3598dc636dda6dde7200ba186e4ea34bddfb#diff-f88531471269535c024c86ed25572f37R35

**Comment by tim-hellhake** [comment]
Basically numbers.
I'll readd the prefix.

**Comment by tim-hellhake** [comment]
One moment please

**Comment by tim-hellhake** [comment]
Ok got it

**Pull request merged**
