### PR TITLE
Add ESP-adapter.

### LINKED ISSUE #25: [new addon] ESP adapter
I've made an adapter than scans a range of IP addresses for devices that respond with a json "Thing" response at http://IPAddress/thing during pairing.  The devices found are configured with Properties from this response.  "ESP" refers to the initial device I targeted, the Wemos Mini (ESP8266).  I've included an example Arduino sketch and also PHP code that runs on an Apache web server.  If you would like to incude it, it is

  {
    "name": "ESP-adapter",
    "display_name": "ESP",
    "description": "Support any web device that can accept/respond with json data",
    "version": "0.3.0",
    "url": "https://github.com/fiz1962/ESP-adapter/archive/0.3.tar.gz",
    "api": {
      "min": 1,
      "max": 1
    }
  }

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #25

### CODE REVIEW

**Comment by hobinjk** [comment]
I think the description should point to documentation about which JSON endpoints are required from the device (i.e. point to the repo) since it's different from the WoT API.

**Comment by fiz1962** [comment]
I'd like to keep it as in line with the WoT API as possible.  Currently the device returns "id" as an addition to the Thing resource and I will change the code to generate an ID internally rather than passing it as part of the json data.  I will also change http://myIP/thing/set?var=val to http://myIP/thing and pass "messageType": "setProperty" and return "messageType": "propertyStatus".

**Comment by mrstegeman** [comment]
@hobinjk there are sample node and PHP "thing" implementations in the git repo, so maybe we just link to the github page?

**Comment by hobinjk** [comment]
Linking to the github page should be good enough to provide context

**Pull request merged**
