### PR TITLE
Add Tradfri adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**

### CODE REVIEW

**Comment by tim-hellhake** [comment]
> Checksum missing for file "/home/runner/work/addon-list/addon-list/package/node_modules/rc/cli.js" in package "tradfri-adapter"

I don't see this file in the package 🤔

**Comment by tim-hellhake** [comment]
```
curl -L https://github.com/tim-hellhake/tradfri-adapter/releases/download/0.1.0/tradfri-adapter-0.1.0.tgz -o tradfri-adapter-0.1.0.tgz
tar -xzf tradfri-adapter-0.1.0.tgz
ls -1 package/node_modules
```

>alcalzone-shared
debug
dns-packet
ip
mdns-server
ms
node-coap-client
node-dtls-client
node-tradfri-client
reflect-metadata
safe-buffer
semver

**Comment by mrstegeman** [comment]
```sh
$ ls -l node_modules/.bin/rc
lrwxr-xr-x 1 mstegeman staff 12 Nov 26 13:52 node_modules/.bin/rc -> ../rc/cli.js
```

I've been adding `rm -rf node_modules/.bin` to my `package.sh` scripts for exactly this reason.

**Comment by tim-hellhake** [comment]
I see. He is following symbolic links.
But why is there a symbolic link if the package is not installed?
I'll remove the bin folder.

**Comment by mrstegeman** [comment]
@tim-hellhake This looks good. Could you update the description, though, to indicate that this is via the Tradfri hub, just to distinguish from the Zigbee's Tradfri support? You don't need to update your package.json/manifest.json, just the file in this PR.

**Comment by tim-hellhake** [comment]
Done

**Pull request merged**
