### PR TITLE
Candle manager 1.0.7

### PR DESCRIPTION
**Pull request by createcandle**
- Can now handle empty #define strings
- Update of Arduino CLI to latest version
- Faster boot by moving init into a thread
- Fixed advanced options not showing up
- Fixed edge case where the list of sketches was multiplied

### CODE REVIEW

**Comment by mrstegeman** [comment]
I see that there's also a darwin binary in this package. Should we add `darwin-x64` to the list of supported platforms?

**Comment by createcandle** [comment]
Yes we should. It's supported.

**Comment by mrstegeman** [comment]
Done.

**Comment by createcandle** [comment]
Thank you

**Pull request merged**
