### PR TITLE
Add basic sonos adapter

### PR DESCRIPTION
**Pull request by freaktechnik**
The adapter currently supports discovering devices, changing volume, play state, shuffle and repeat all (including listening for changes to those states).

### CODE REVIEW

**Comment by freaktechnik** [comment]
Sorry about all the misplaced comas :(

**Comment by mrstegeman** [comment]
@freaktechnik No worries! I'm actually going to need you to update your package, though. All of your dependencies, i.e. `sonos`, need to be included in the tarball. You could use something [like this](https://github.com/mozilla-iot/philips-hue-adapter/blob/master/package.sh).

**Comment by freaktechnik** [comment]
I've created an update package. Should it also include `SHA256SUMS` like hue does? I couldn't find anything mentioning that file.

**Comment by mrstegeman** [comment]
Yes, it needs to include `SHA256SUMS` as well.

**Comment by freaktechnik** [comment]
Okay, uploaded a package including the SHA256SUMS file.

**Comment by freaktechnik** [comment]
(I would also recommend to update the https://github.com/mozilla-iot/addon-list#packaging-add-ons section accordingly)

**Comment by mrstegeman** [comment]
@freaktechnik Let us know when you need your add-on updated!

**Comment by freaktechnik** [comment]
@mrstegeman sure, thank you very much for adding it to the official list!

**Pull request merged**
