### PR TITLE
Update enocean adapter to 0.1.6

### PR DESCRIPTION
**Pull request by tim-hellhake**
Please run the addon builder and add the checksums.

https://github.com/tim-hellhake/enocean-adapter/issues/7

### CODE REVIEW

**Comment by mrstegeman** [comment]
@tim-hellhake All the builds are failing due to the ancient version of `serialport` required by `node-enocean`. It looks `node-enocean` has been superseded by [`enocean-js`](https://www.npmjs.com/package/enocean-js). Would it be possible to switch to that?

**Comment by tim-hellhake** [comment]
Last time I looked the device support was very basic.
I'll check if everything works with `enocean-js`.

**Comment by tim-hellhake** [comment]
`enocean-js` still looks very unfinished.
The library is split into multiple small modules but there is almost no documentation on how to combine them.
I'm able to receive EnOcean telegrams but only in the raw form.
I found a parser for the telegrams but I've no idea how to use it.

**Comment by mrstegeman** [comment]
Well, shoot. How much effort would it be for you to fork `node-enocean` and just update the `serialport` version?

**Comment by tim-hellhake** [comment]
This should work now.
I tested it locally with node 10.

**Pull request merged**
