### PR TITLE
Update Slack adapter to 0.2.0

### PR DESCRIPTION
**Pull request by tim-hellhake**
tim-hellhake/slack-adapter#2

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Working on it

**Comment by mrstegeman** [comment]
Your `package.json` needs to be updated with `notifier` as well.

Also, just FYI, you used Prowl instead of Slack in [your code](https://github.com/tim-hellhake/slack-adapter/blob/master/index.js#L16-L17). 😃

**Comment by tim-hellhake** [comment]
> Your package.json needs to be updated with notifier as well.

I did not specify one.
I assume `adapter` is the default?

> Also, just FYI, you used Prowl instead of Slack in your code. 😃

Damn, thanks for the hint.

**Comment by mrstegeman** [comment]
Yes, adapter is the default. You can change it [like this](https://github.com/mozilla-iot/pushover-notifier/blob/master/package.json#L33).

**Pull request merged**
