### PR TITLE
Square Theme 0.0.1

### PR DESCRIPTION
**Pull request by flatsiedatsie**

### CODE REVIEW

**Comment by flatsiedatsie** [comment]
"none" still doesn't work?

**Comment by flatsiedatsie** [comment]
round-icons

Here's what I mean: some of the icons have the circle baked in. It's part of the icon image.

**Comment by mrstegeman** [comment]
If you remove this `margin-right` rule, I'll be happy with this: https://github.com/flatsiedatsie/square-theme/blob/master/css/extension.css#L175

**Comment by mrstegeman** [comment]
Oh, also, please remove this whole rule block: https://github.com/flatsiedatsie/square-theme/blob/master/css/extension.css#L20-L23

There's no reason to rewrite the header, and it ends up being on top of icons when you're scrolling on a small screen.

**Comment by flatsiedatsie** [comment]
Agreed, that was just a bit of silly fun.

**Comment by mrstegeman** [comment]
@flatsiedatsie https://github.com/flatsiedatsie/square-theme/pull/1

This prevents your extension from running code every 50 ms.

**Comment by flatsiedatsie** [comment]
Thank you for your wonderful improvements!

**Comment by mrstegeman** [comment]
My only gripe now is the blue on blue. Something to think about in the near future, as the lack of contrast is not very great for accessibility.

Screenshot_2019-11-20 WebThings Gateway

**Comment by flatsiedatsie** [comment]
Haha, timing. I found an error in your code which I just fixed. I'll create a new pull request :-)

**Comment by mrstegeman** [comment]
Oops!

**Pull request merged**
