### PR TITLE
first release of calendar adapter

### PR DESCRIPTION
**Pull request by chas-iot**
This adapter provides calendar management of the working week, holidays, and other event dates. This is to support rules such as not switching on a wakeup alarm on public or personal holidays, or triggering an automatic light display on a birthday.

First release
- a singleton thing
- 4 Properties
-- isHoliday
-- isWorkingDay
-- reason (for date significance)
-- rulesTag (may be useful for rules)
- updated each day (checked each hour, to allow for timezones, daylight savings)
- configuration sheet to setup working week and significant dates (holidays, vacations, etc)

### CODE REVIEW

**Comment by mrstegeman** [comment]
This looks useful! I have a couple small suggestions, for the add-on preferences.

1. Making the dateType an `enum` would make things simpler for the user.
2. Adding a `description` and/or `title` for each of the preferences would make them clearer.

**Comment by chas-iot** [comment]
I'll look and see what I can do, almost certainly following your suggestion.

It worked out this way 'cos the adapter grew organically and changed shape, so the approach meant that I didn't have to re-input 20 holiday dates.

I started to integrate the first (free) holiday api provider and node-fetch is not behaving itself (though given my history, I know I'll find that it's my misbehaviour :) ). This led me to a concern about the screen real-estate required for each holiday. For the API integration, I have to add a further read-only field to handle the date of a holiday changing. For example, some Islamic holidays are set approximately at the start of the year and firmed up close to the actual date based on observations of the moon.

**Comment by mrstegeman** [comment]
Well, I'll leave it up to you what should happen here. I can merge as is, or we can wait for some of those changes. Let me know what you'd prefer.

**Comment by chas-iot** [comment]
I made changes along the lines you suggested. The release should be OK, I just forgot to upload the package before I sent the update to the pull request.

**Pull request merged**
