### PR TITLE
Update rf433 adapter to 0.1.3

### PR DESCRIPTION
**Pull request by tim-hellhake**
Please run the addon builder and add the checksum.

tim-hellhake/rf433-adapter#2

### CODE REVIEW

**Comment by mrstegeman** [comment]
Build is failing: https://github.com/mozilla-iot/addon-builder/runs/414524418?check_suite_focus=true

**Comment by mrstegeman** [comment]
@tim-hellhake where is the `rc-switch` stuff supposed to be coming from?

**Comment by mrstegeman** [comment]
@tim-hellhake I'm going to merge this, unless you have any objections. The missing wiringpi dependency was already an issue, but will be resolved for everybody with mozilla-iot/gateway#2417.

**Comment by tim-hellhake** [comment]
I think you can merge it.
With wiringpi installed, everything should be fine.

**Pull request merged**
