### PR TITLE
Added new openwrt arch (for turris omnia)

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by dhylands** [comment]
I also removed any of the adpaters which require bluetooth, since they can't work right now.

**Comment by mrstegeman** [comment]
Travis failed. One of the lg-tv-adapter packages is still linux-arm.

**Comment by dhylands** [comment]
I also removed any openwrt v10 adapters since we don't even have node v10 for openwrt.

**Comment by mrstegeman** [comment]
Could we just make the builder script skip v10 for OpenWrt?

**Pull request merged**
