### PR TITLE
Add Google Home adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**

### CODE REVIEW

**Comment by mrstegeman** [comment]
The `files` array in your `package.json` is invalid.

**Comment by mrstegeman** [comment]
Still failing with the same error.

```
File missing for package "google-home-adapter": index.js
```

**Comment by mrstegeman** [comment]
```
2019-06-24 14:03:43.066 ERROR  : google-home: TypeError: Class constructor Adapter cannot be invoked without 'new'
2019-06-24 14:03:43.066 ERROR  : google-home:     at new GoogleHomeAdapter (/Users/mstegeman/.mozilla-iot/addons/google-home-adapter/lib/google-home-adapter.js:126:28)
2019-06-24 14:03:43.066 ERROR  : google-home:     at module.exports (/Users/mstegeman/.mozilla-iot/addons/google-home-adapter/lib/index.js:8:61)
2019-06-24 14:03:43.067 ERROR  : google-home:     at pluginClient.register.catch.then (/Users/mstegeman/workspace/gateway/src/addon-loader.js:96:9)
2019-06-24 14:03:43.067 ERROR  : google-home:     at <anonymous>
2019-06-24 14:03:43.067 ERROR  : google-home:     at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by mrstegeman** [comment]
Great, running now. I've got @kgiori testing it for me, since I don't have a Google Home to test with.

**Comment by kgiori** [comment]
wow, thanks @tim-hellhake -- this add-on is super fun!! I just told my hubby happy anniversary (which is today) via my G home speaker! it also works on Google TV, since that has Chromecast capability as well. Would it be possible to send images or videos to the Google TV? From my ONVIF camera for example?

**Comment by kgiori** [comment]
@tim-hellhake also thinking about Chromecast and audio feeds... I've been thinking for a while about how to use the gateway or something similar to create a *private* video calling system.... hmmm...

**Comment by benfrancis** [comment]
I suggest renaming this add-on to more accurately reflect what it does, as simply calling it "Google Home" will probably make people think it allows you to control all the devices attached to the gateway using Google Home.

Perhaps something like "Google Home Text to Speech".

Also, note that the existing Chromecast add-on already detects the Google Home Hub but provides different functionality. It might be a good idea to test these two add-ons together to check they don't conflict with each other.

**Comment by mrstegeman** [comment]
@benfrancis I assume you’re talking about the Chromecast add-on? Would it make sense to merge the two?

**Comment by tim-hellhake** [comment]
@hobinjk renamed

**Comment by tim-hellhake** [comment]
@mrstegeman There are some features I want to add which are google home specific.

**Pull request merged**
