### PR TITLE
MySensors 1.1.0

### PR DESCRIPTION
**Pull request by createcandle**
Small modifications

### CODE REVIEW

**Comment by mrstegeman** [comment]
Similar to the Candle manager add-on, you're including compiled dependencies (when this package is set to run on any architecture) and also running `boostrap.py`.

**Comment by mrstegeman** [comment]
https://github.com/createcandle/Webthings-mysensors-adapter/pull/10

**Comment by createcandle** [comment]
Thank you for this. It's hard to stay aware of what is best practice with the Gateway.

Talking about which: what exactly is the add-on builder? What's its goal? And what is its effect on developing addons?

**Comment by mrstegeman** [comment]
Please merge the PR I just opened and I'll add your add-on to the [addon-builder](https://github.com/mozilla-iot/addon-builder).

**Comment by mrstegeman** [comment]
Still waiting on this: https://github.com/createcandle/Webthings-mysensors-adapter/pull/11

**Pull request merged**
