### PR TITLE
New MyQ Adapter

### PR DESCRIPTION
**Pull request by kennethklee**
Adds a new MyQ adapter for Chamberlain garage doors

### CODE REVIEW

**Comment by mrstegeman** [comment]
This is great! Could you test and merge https://github.com/kennethklee/webthings-myq-adapter/pull/1 first?

**Comment by kennethklee** [comment]
force pushed because commit should have been a `fix` instead of `feat`

**Comment by mrstegeman** [comment]
Looks like you forgot to update the version in `manifest.json`.

**Comment by kennethklee** [comment]
rebuilt the package and updated checksum. you may need to reupload to s3

**Comment by mrstegeman** [comment]
@kennethklee I built a new release with https://github.com/kennethklee/webthings-myq-adapter/pull/2.

**Pull request merged**
