### PR TITLE
first release of adaptor for Singapore Pollutant Standards Index

### PR DESCRIPTION
**Pull request by chas-iot**
This is the first time I've submitted an adapter, so I likely have something not quite right

### CODE REVIEW

**Comment by chas-iot** [comment]
I'm missing something regarding the checksums, any hints?

I manually ran `sha256sum psi-sg-0.1.2.tgz` and got the same failing results as earlier

**Comment by tim-hellhake** [comment]
The checksum seems to be wrong.

```
curl https://github.com/chas-iot/psi-sg/releases/download/v0.1.2/psi-sg-0.1.2.tgz -L 2> /dev/null | sha256sum
b7109e10f50bc33b54b43db73350a5264bb8dfb90a4931be6d365399b2511646
```

**Comment by chas-iot** [comment]
hrm, looks quite odd to me. When I download the file from github and run sha256sum, I get the same result as you.
when I run it on the locally generated file, I get that different hash.

possibly, this is an artefact of doing my development split across Windows and Ubuntu

**Comment by tim-hellhake** [comment]
Are you sure that the locally generated file is still the same as the uploaded one?
To narrow down the error, you could generate a new file, upload it and check if the downloaded file has a different hash.

**Comment by tim-hellhake** [comment]
Btw. your checksum file contains the correct checksum.
```
curl -L https://github.com/chas-iot/psi-sg/releases/download/v0.1.2/psi-sg-0.1.2.tgz.sha256sum
b7109e10f50bc33b54b43db73350a5264bb8dfb90a4931be6d365399b2511646  psi-sg-0.1.2.tgz
```

**Comment by chas-iot** [comment]
The local file is _not_ the same as the uploaded one. I suspect (before investigating) that my upload process replaced LF with CRLF. After dinner , I'll look into where my process broke down

**Comment by tim-hellhake** [comment]
> The local file is not the same as the uploaded one. I suspect (before investigating) that my upload process replaced LF with CRLF

Correct if I'm wrong but wasn't the checksum filed created before the upload?
The fact that it contains the checksum of the uploaded file suggests that the archive did not change during the upload.

**Comment by chas-iot** [comment]
is there a way to re-run the checks without a new commit?

**Comment by mrstegeman** [comment]
`Homepage mismatch for package "psi-sg": homepage_url from manifest.json "https://github.com/mozilla-iot/psi-sg#readme" doesn't match homepage_url from list.json "https://github.com/chas-iot/psi-sg#readme"`

**Comment by chas-iot** [comment]
finally! :)

**Comment by chas-iot** [comment]
Thank-you @tim-hellhake , @mrstegeman

**Pull request merged**
