### PR TITLE
Add insteon-adapter-1.0.0

### PR DESCRIPTION
**Pull request by snorp**
Fixes mozilla-iot/gateway#620

### CODE REVIEW

**Comment by snorp** [comment]
Fixed in insteon-adapter master

**Comment by mrstegeman** [comment]
```
Checksum missing for file "/home/runner/work/addon-list/addon-list/package/node_modules/node-abi/node_modules/.bin/semver" in package "insteon-adapter"
```

Please add an `rm -rf ./node_modules/.bin` to your `package.sh`.

**Comment by snorp** [comment]
I already have that[1], so I'm confused about what's going wrong here...

[1] https://github.com/snorp/insteon-adapter/blob/master/package.sh#L23

**Comment by mrstegeman** [comment]
Looks like that's actually a nested node_modules.

You should do one of these:
```sh
# sha256sum both files and symlinks
find node_modules -type f -exec sha256sum {} \; >> SHA256SUMS
find node_modules -type l -exec sha256sum {} \; >> SHA256SUMS

# remove the symlinks
find node_modules -type d -name .bin -exec rm -rf {} \;
```

**Comment by snorp** [comment]
Alright, pushed that to master.

**Comment by mrstegeman** [comment]
You were supposed to choose one of those options, not both. 😄 That's going to lead to invalid checksums.

**Comment by snorp** [comment]
Ok, I really don't understand what this thing is trying to do. Why do we ever need to delete stuff at all?

**Comment by snorp** [comment]
I removed the `rm -rf` line now.

**Comment by mrstegeman** [comment]
The `.bin` directories contain a bunch of symlinks, so either those need to be checksummed or just deleted (since they're not actually used).

**Pull request merged**
