### PR TITLE
Update ruuvitag adapter (addon-builder)

### PR DESCRIPTION
**Pull request by tim-hellhake**
https://github.com/tim-hellhake/ruuvitag-adapter/issues/10

### CODE REVIEW

**Comment by mrstegeman** [comment]
Looks like you forgot to add `lib/ruuvitag-parser.js` to the `files` array in `package.json`.

**Comment by tim-hellhake** [comment]
Sorry, I missed that.
The missing entry in the `files` array should now be present.
I also used the chance to include new features 😬.

**Comment by mrstegeman** [comment]
The build is failing now:

```
> tsc -p .

src/ruuvitag-adapter.ts:96:7 - error TS2339: Property 'txPower' does not exist on type 'DataV3 | DataV5'.

96       txPower,
         ~~~~~~~


Found 1 error.
```

**Comment by tim-hellhake** [comment]
I fixed the build error.
It should work now.
The version remains `0.2.0`.

**Comment by mrstegeman** [comment]
Now `lib/ruuvitag-parser.spec.js` is missing from the `files` array in `package.json`.

**Comment by tim-hellhake** [comment]
I added it to the array.
Should be the last one 😅

**Pull request merged**
