### PR TITLE
Privacy Manager 0.0.1

### PR DESCRIPTION
**Pull request by createcandle**
An add-on that allows users to change and remove data from their logs, as well as remove internal logs files.

### CODE REVIEW

**Comment by createcandle** [comment]
privacy_manager_data_sculptor

privacy_manager_internal_logs

**Comment by mrstegeman** [comment]
This is really cool! I've left some notes below.

Please fix:
* Filter out `run-app.log` from your list of internal log files. It's just a symlink to the latest log.
* The list of internal logs is not updating properly after I delete one. The list shrinks by one, but the proper file is not removed from the list.

Suggestions:
* You're importing some things you don't need here: https://github.com/createcandle/privacy-manager/blob/master/pkg/privacy_manager.py#L22
  * Also, you should probably `sys.exit(1)` if those imports fail, instead of just logging. Everything is going to crash anyway.
* You're opening the database twice here (and some other places): https://github.com/createcandle/privacy-manager/blob/master/pkg/privacy_manager.py#L318-L319
* Don't use a POST request when you really just need a GET. Similarly, you could use a DELETE when you're actually deleting something.
* Check out `self.user_profile` in your APIHandler class. It already has the log directory, so that you're not assuming it's `~/.mozilla-iot/log`. It could really be anywhere.
* You have an Arduino log at the bottom.

**Comment by kgiori** [comment]
Indeed, a valuable contribution to improve privacy. At first glance I had some quick thoughts on wording suggestions. 
Sculptor => "Data Sculptor"? "Data Logs"? "Log Sculptor"?
Internal => "System" or "System Files"? or "System Logs"?
Would this add-on page show up some place such as under Settings=> Developer? Or would the UI be found by clicking on the add-on "Configure" option?

**Comment by mrstegeman** [comment]
@kgiori It adds an entry to the main UI menu.

**Comment by createcandle** [comment]
- fixed log deletion bug
- extra imports removed
- double database opening removed
- subprocess function removed.

Thanks for the tip on `self.user_profile`, that sounds really useful.

For now I'll stick to `post` since for code re-usability it's handy to have one version that 'always works'.

**Comment by mrstegeman** [comment]
@flatsiedatsie The author in this PR doesn't match what you have in your `manifest.json` - "Candle" vs. "CreateCandle". They need to match.

**Pull request merged**
