### PR TITLE
Add Http adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**

### CODE REVIEW

**Comment by mrstegeman** [comment]
This is a great, flexible addition.

A couple suggestions I have (feel free to argue or ignore):
* Should the method be configurable, such that the user could select GET instead of POST?
* Should the content type be configurable?
* Instead of manually building up the request body, you could use [URLSearchParams](https://nodejs.org/api/url.html#url_class_urlsearchparams).

**Comment by tim-hellhake** [comment]
@mrstegeman thanks for the suggestions.
I think I got all points covered.
What do you think?

**Comment by mrstegeman** [comment]
Looks great! One small nitpick: POST/PUT requests could technically have both body parameters _and_ query parameters.

**Comment by tim-hellhake** [comment]
Thanks :)
Damn, I knew I must have missed something.
That was the reason I separated query and body params.

**Comment by tim-hellhake** [comment]
Done :)

**Comment by mrstegeman** [comment]
Perfect! One tiny request: can you make the display name all uppercase, i.e. "HTTP" instead of "Http"?

**Comment by tim-hellhake** [comment]
Sure!

**Pull request merged**
