### PR TITLE
New version of voco

### PR DESCRIPTION
**Pull request by createcandle**
- tested for 0.10.0 of the Gateway
- More frequent injection of changed names into Snips
- Updated to latest version of Snips

### CODE REVIEW

**Comment by mrstegeman** [comment]
URL appears to be invalid.

**Comment by mrstegeman** [comment]
```
File missing for package "voco": manifest.json
```

**Comment by flatsiedatsie** [comment]
Ah darn. I won't be able to fix it for a few days.

**Comment by mrstegeman** [comment]
Looks like you included a file you shouldn't have:

```
Checksum failed in package "voco": package/./pkg/._voco_adapter.py
```

**Pull request merged**
