### PR TITLE
Add counter adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**

### CODE REVIEW

**Comment by mrstegeman** [comment]
A couple thoughts.

1. Could you provide a more useful description, with a use case or something? Kind of vague.
2. It's a bit limiting with just one counter device, in my opinion. Maybe add a config option for multiple counters, sort of like the pulse and timer adapters?

**Comment by tim-hellhake** [comment]
Timers are now created via the config option.
I hope the description is ok now.

**Comment by mrstegeman** [comment]
I like this description better, thanks.

One other issue. You probably should not use the user-provided name in the ID, as it could lead to unfortunate issues like this: https://github.com/mozilla-iot/pulse-adapter/issues/6

**Comment by tim-hellhake** [comment]
Good point, the id is now generated from the index

**Comment by mrstegeman** [comment]
New problem. If the user deletes a counter, all the indices will change. A better thing to do is to auto-generate an ID for each counter and store it in the database. See:
* https://github.com/mozilla-iot/virtual-things-adapter/blob/master/package.json#L72-L84
* https://github.com/mozilla-iot/virtual-things-adapter/blob/master/virtual-things-adapter.js#L1079-L1084
* https://github.com/mozilla-iot/virtual-things-adapter/blob/master/virtual-things-adapter.js#L1184

Secondary question: do you think it would be better to persist the counter somehow, that way it remains the same when the gateway restarts or something? Just a thought.

**Comment by tim-hellhake** [comment]
> A better thing to do is to auto-generate an ID for each counter and store it in the database.

Neat trick with the `"readOnly": true` property.

> do you think it would be better to persist the counter somehow, that way it remains the same when the gateway restarts or something?

Good idea. I'll add that.

**Comment by tim-hellhake** [comment]
Whats new:

On start:
- Generate a random id for all timers which don't have one
- Load last count from settings

On change:
- Persist new count to settings

**Pull request merged**
