### PR TITLE
Add RF433 adapter

### PR DESCRIPTION
**Pull request by tim-hellhake**
This should fix https://github.com/mozilla-iot/gateway/issues/682 when I'm finished.
Currently only receiving is implemented.

### CODE REVIEW

**Comment by tim-hellhake** [comment]
@mrstegeman Should be fine now

**Comment by mrstegeman** [comment]
@kgiori Could you give this a try, since I don't have any hardware to test with?

```bash
cd ~/.mozilla-iot/addons
wget https://github.com/tim-hellhake/rf433-adapter/releases/download/0.1.1/rf433-adapter-0.1.1.tgz
tar xzf rf433-adapter-0.1.1.tgz
rm rf433-adapter-0.1.1.tgz
mv package rf433-adapter
sudo systemctl restart mozilla-iot-gateway
```

Then, enable the add-on in the UI.

**Comment by mrstegeman** [comment]
@tim-hellhake It looks like there is some native code here. Do you want this run through the addon-builder, or do you just want to do a Pi-only build?

**Comment by tim-hellhake** [comment]
Sorry, I forgot to change the arch.
I'm using [rc-switch](https://github.com/sui77/rc-switch) to control a simple rf433 receiver like the one mentioned in https://github.com/mozilla-iot/gateway/issues/682.
rc-switch only supports raspberry pi and Arduino so I think I just build the package on my pi for now.

**Comment by tim-hellhake** [comment]
Maybe @sindastra could test it?

**Comment by mrstegeman** [comment]
Could you also update the description (and your README) to indicate that some extra hardware is required?

**Comment by tim-hellhake** [comment]
> Could you also update the description (and your README) to indicate that some extra hardware is required?

Already on it 😄

**Comment by tim-hellhake** [comment]
@mrstegeman Is the description check still in place?
I would have expected https://github.com/mozilla-iot/addon-list/pull/387/commits/d0561bd474f3a8091c0106fa19e412e2f32e7243 to fail.
I just changed the description in the addon list but the package was the same.

**Comment by mrstegeman** [comment]
The descriptions are actually not compared between the two, that way you could have some separate instructions or something in `package.json` for post-install.

**Comment by sindastra** [comment]
@tim-hellhake I will try this out as soon as I get a chance, sorry I wasn't around much

**Pull request merged**
