### PR TITLE
Update tradfri adapter to 0.1.3

### PR DESCRIPTION
**Pull request by tim-hellhake**
Please add the adapter to the addon builder and add the checksums.

tim-hellhake/tradfri-adapter#1

### CODE REVIEW

**Comment by mrstegeman** [comment]
You're going to have to update your `package.sh` so we can cross-compile.

**Comment by tim-hellhake** [comment]
I updated the `package.sh`.

**Comment by mrstegeman** [comment]
Looks like typescript is failing now:

```
File missing for package "tradfri-adapter": lib/index.js
```

**Comment by tim-hellhake** [comment]
The sources should be included now.

**Pull request merged**
