### PR TITLE
Add enocean addon

### PR DESCRIPTION
**Pull request by tim-hellhake**
Resolves https://github.com/mozilla-iot/gateway/issues/1392

### CODE REVIEW

**Comment by mrstegeman** [comment]
I opened a small PR for you. Other than that, things look good.

**Comment by tim-hellhake** [comment]
PR is merged and I also updated the name and description to `EnOcean`

**Comment by mrstegeman** [comment]
`list.json` changes are good now. Can you remove whatever the binary `abc` file is?

**Comment by tim-hellhake** [comment]
Sorry, I didn't saw the file.
I rewrote the last commit to ensure the file is not part of the history.

**Comment by mrstegeman** [comment]
So, there's another issue with this. Some of the node modules have compiled dependencies, so we'll need to cross-compile. If you don't want to do that yourself, I can pull it into our [addon-builder](https://github.com/mozilla-iot/addon-builder) and do it for you. You'll just have to let us know when you'd like a new release built.

If you'd like to go that route, can you update your `package.sh` script to be similar to [this one](https://github.com/mozilla-iot/zigbee-adapter/blob/master/package.sh)?

**Comment by tim-hellhake** [comment]
How do I find out if a module needs to be cross-compiled?
If it's not to much work I would prefer to use the [addon-builder](https://github.com/mozilla-iot/addon-builder).
It's already known to cross compile the right binaries.
Currently, I have no `package-lock.json` in the repo.
Would it be better to include one for stable builds or does it break the cross compile chain?

**Comment by mrstegeman** [comment]
What I do is:

```
find node_modules -name '*.node'
```

If anything comes up, there are native modules. A `package-lock.json` would ensure that the add-on gets built with the dependencies you want, instead of the latest, so you should probably add it to be safe.

**Comment by tim-hellhake** [comment]
Ok i added a `package-lock.json`

**Comment by mrstegeman** [comment]
Opened one more PR for you.

**Comment by tim-hellhake** [comment]
Merged

**Comment by mrstegeman** [comment]
Success! Will you remove your local copy and installed through this through the UI, just to make sure things function properly?

**Comment by tim-hellhake** [comment]
Works as expected.
Thank you!

**Pull request merged**
