### PR TITLE
Update version 0.0.3

### PR DESCRIPTION
**Pull request by damooooooooooh**
Added ability to control lights and sirens.  Fixed broken ring api library.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Try adding an `rm -rf ./node_modules/.bin` in your `package.sh`.

**Comment by mrstegeman** [comment]
Ugh, node is a pain in the butt sometimes.

```
Checksum missing for file "/home/runner/work/addon-list/addon-list/package/node_modules/execa/node_modules/.bin/node-which" in package "ring-adapter"
```

Try this one:
```sh
find . -type d -name .bin -exec rm -rf {} \;
```

**Comment by damooooooooooh** [comment]
Hey, I'm using a Mac and when I exec sha256sum on the find command it excludes files found in hidden directories...

find node_modules -type f -exec sha256sum {} \; >> SHA256SUMS

If I run 

find node_modules -type f 

it returns the hidden files/folders fine

Never encountered this before.  Not sure if Mac specific

**Comment by mrstegeman** [comment]
I'd recommend doing a `brew install findutils` and using `find` from that package. I've encountered quite a few issues with the native version.

**Comment by damooooooooooh** [comment]
Issue was related to symbolic links, find wasn't processing them using the -type f switch.  All working now.

**Pull request merged**
