### PR TITLE
Voice-Addon 0.3

### PR DESCRIPTION
**Pull request by andrenatal**
Setup step on 0.2 was broken.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Why is the `snips-injection` package unconditionally installed now?
https://github.com/andrenatal/voice-addon/commit/091d0555c3c3976547e18a918194387739d19fb0#diff-e0d952f96abca7e07c33dea40a09a4d0R40

Also, wouldn't it make more sense to move files into `/etc/` and `/usr/share/snips` _after_ installing the snips packages, as it was before?

**Comment by andrenatal** [comment]
1 - Because `dpkg -s snips-install` returns success even if the package is installed:

```
pi@gateway:~/.mozilla-iot/addons $ sudo apt-get remove snips-injection
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'snips-injection' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libev4 libttspico-data libttspico-utils libttspico0 libuv1 libwebsockets8 mosquitto
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.
pi@gateway:~/.mozilla-iot/addons $ dpkg -s snips-injection
Package: snips-injection
Status: deinstall ok config-files
Priority: optional
Section: utility
Installed-Size: 96526
Maintainer: Kevin Lefevre <kevin.lefevre@snips.ai>
Architecture: armhf
Version: 0.60.1
Config-Version: 0.60.1
Replaces: snips-asr-injection (<< 0.58.0)
Provides: snips-asr-injection
Depends: snips-platform-common (>= 0.60.1~), snips-platform-common, snips-platform-common (<< 0.61.1), snips-kaldi
Breaks: snips-asr-injection (<< 0.58.0)
Description: A CLI tool to manage words injection into Snips ASR models
Standards-Version: 3.9.4
```

2 - There's a bug in their platform that if the expected structure of folders isn't created prior starting their services, will break them until reboot the OS.

**Comment by mrstegeman** [comment]
Very weird. Ok.

**Comment by andrenatal** [comment]
Their words:

```

Hi Andre

snips-injection doesn't seems to load correctly the assistant folder.

There is a known bug in the 0.60.1 version (a fix will be pushed in the next release) that prevent any component (snips-asr, snips-nlu, etc) to load an assistant without the following structures:
> /custom_asr/
> /custom_dialogue/
> /custom_hotword/
> /nlu_engine/
> /assistant.json

Can you check if your assistant have everything ?
If any of the above directories is missing, I suggest you to just create an empty folder.
```

**Comment by andrenatal** [comment]
This is now working. I'll just merge so @kgiori  and I can test it here in the office

**Pull request merged**
